/**
 * Code generator — turns a Blueprint into a real, runnable Vite + React + TS
 * + Tailwind project. The generated app reads the blueprint from
 * `src/data/blueprint.ts` and renders it through typed section components,
 * so every project exports as working code (`npm install && npm run dev`).
 */

import type { AppFile, Blueprint, SectionType } from "@/types";
import { slugify } from "@/lib/utils";

function usedSectionTypes(bp: Blueprint): Set<SectionType> {
  const set = new Set<SectionType>();
  for (const page of bp.pages) for (const s of page.sections) set.add(s.type);
  if (bp.features.auth) set.add("login");
  return set;
}

// ---------------------------------------------------------------------------
// Static project files
// ---------------------------------------------------------------------------

function packageJson(bp: Blueprint): string {
  return JSON.stringify(
    {
      name: slugify(bp.name),
      private: true,
      version: "0.1.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "tsc && vite build",
        preview: "vite preview",
      },
      dependencies: {
        react: "^18.3.1",
        "react-dom": "^18.3.1",
        ...(bp.features.supabase.enabled
          ? { "@supabase/supabase-js": "^2.45.0" }
          : {}),
      },
      devDependencies: {
        "@types/react": "^18.3.3",
        "@types/react-dom": "^18.3.0",
        "@vitejs/plugin-react": "^4.3.1",
        autoprefixer: "^10.4.19",
        postcss: "^8.4.40",
        tailwindcss: "^3.4.7",
        typescript: "^5.5.4",
        vite: "^5.3.5",
      },
    },
    null,
    2
  );
}

const VITE_CONFIG = `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
`;

const TSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      target: "ES2020",
      useDefineForClassFields: true,
      lib: ["ES2020", "DOM", "DOM.Iterable"],
      module: "ESNext",
      skipLibCheck: true,
      moduleResolution: "bundler",
      allowImportingTsExtensions: true,
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
      jsx: "react-jsx",
      strict: true,
    },
    include: ["src"],
  },
  null,
  2
);

function indexHtml(bp: Blueprint): string {
  return `<!DOCTYPE html>
<html lang="en" class="${bp.theme.mode}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${bp.name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

const POSTCSS = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;

function tailwindConfig(bp: Blueprint): string {
  return `/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        accent: "${bp.theme.accent}",
      },
      borderRadius: {
        app: "${bp.theme.radius}px",
      },
    },
  },
  plugins: [],
};
`;
}

function indexCss(bp: Blueprint): string {
  const dark = bp.theme.mode === "dark";
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --accent: ${bp.theme.accent};
  --bg: ${dark ? "#0b0c10" : "#f6f7f9"};
  --surface: ${dark ? "#13141a" : "#ffffff"};
  --border: ${dark ? "rgba(255,255,255,0.09)" : "rgba(15,18,25,0.1)"};
  --text: ${dark ? "#eceef2" : "#171a21"};
  --muted: ${dark ? "#9aa1ad" : "#5d6470"};
}

body {
  background: var(--bg);
  color: var(--text);
  font-family: ${
    bp.theme.font === "serif"
      ? "Georgia, serif"
      : bp.theme.font === "mono"
        ? "'SF Mono', Consolas, monospace"
        : "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
  };
  -webkit-font-smoothing: antialiased;
}

.card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: ${bp.theme.radius}px;
  padding: 1.25rem;
}
`;
}

const MAIN_TSX = `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;

// ---------------------------------------------------------------------------
// Blueprint data file
// ---------------------------------------------------------------------------

function blueprintData(bp: Blueprint): string {
  return `/**
 * App blueprint — generated by ForgeAI.
 * Edit this file to change content; components render from it.
 */
import type { Blueprint } from "../types";

export const blueprint: Blueprint = ${JSON.stringify(
    { ...bp },
    null,
    2
  )};
`;
}

function typesFile(): string {
  return `// Shared types for the generated app (mirrors ForgeAI's blueprint schema).

export type SectionType =
  | "hero" | "stats" | "chart" | "table" | "cards" | "pricing" | "form"
  | "todo" | "booking" | "testimonials" | "cta" | "login" | "activity" | "custom";

export interface Section {
  type: SectionType;
  [key: string]: unknown;
}

export interface Page {
  id: string;
  name: string;
  icon: string;
  sections: Section[];
}

export interface Blueprint {
  appType: string;
  name: string;
  tagline: string;
  description: string;
  theme: {
    mode: "dark" | "light";
    accent: string;
    accentName: string;
    radius: number;
    font: string;
    premium: boolean;
  };
  pages: Page[];
  features: {
    auth: boolean;
    responsive: boolean;
    supabase: {
      enabled: boolean;
      auth: boolean;
      database: boolean;
      storage: boolean;
      edgeFunctions: boolean;
    };
  };
}
`;
}

// ---------------------------------------------------------------------------
// Generated components (static templates, blueprint-driven)
// ---------------------------------------------------------------------------

const COMPONENT_SOURCES: Record<string, string> = {
  "Layout.tsx": `import { useState } from "react";
import { blueprint } from "../data/blueprint";

interface LayoutProps {
  activePage: string;
  onNavigate: (id: string) => void;
  children: React.ReactNode;
}

export default function Layout({ activePage, onNavigate, children }: LayoutProps) {
  const [open, setOpen] = useState(false);
  return (
    <div className="flex min-h-screen">
      <aside
        className={
          "w-56 shrink-0 border-r p-4 flex flex-col gap-1 max-md:fixed max-md:inset-y-0 max-md:left-0 max-md:z-30 max-md:transition-transform " +
          (open ? "max-md:translate-x-0" : "max-md:-translate-x-full")
        }
        style={{ borderColor: "var(--border)", background: "var(--surface)" }}
      >
        <div className="flex items-center gap-2 px-2 pb-5 font-bold">
          <span
            className="flex h-7 w-7 items-center justify-center rounded-lg text-white text-xs"
            style={{ background: "var(--accent)" }}
          >
            {blueprint.name[0]}
          </span>
          {blueprint.name}
        </div>
        {blueprint.pages.map((p) => (
          <button
            key={p.id}
            onClick={() => {
              onNavigate(p.id);
              setOpen(false);
            }}
            className="rounded-lg px-3 py-2 text-left text-sm font-medium transition-colors"
            style={
              activePage === p.id
                ? { background: "color-mix(in srgb, var(--accent) 15%, transparent)", color: "var(--text)" }
                : { color: "var(--muted)" }
            }
          >
            {p.name}
          </button>
        ))}
      </aside>
      <div className="min-w-0 flex-1">
        <header
          className="flex items-center justify-between border-b px-6 py-3"
          style={{ borderColor: "var(--border)" }}
        >
          <div className="flex items-center gap-3">
            <button className="md:hidden rounded border px-2 py-1 text-sm" style={{ borderColor: "var(--border)" }} onClick={() => setOpen(!open)}>
              ☰
            </button>
            <h1 className="text-base font-semibold">
              {blueprint.pages.find((p) => p.id === activePage)?.name ?? blueprint.name}
            </h1>
          </div>
          <div
            className="flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold text-white"
            style={{ background: "var(--accent)" }}
          >
            {blueprint.name.slice(0, 2).toUpperCase()}
          </div>
        </header>
        <main className="mx-auto flex max-w-5xl flex-col gap-6 p-6">{children}</main>
      </div>
    </div>
  );
}
`,

  "SectionRenderer.tsx": `import type { Section } from "../types";
__IMPORTS__

export default function SectionRenderer({ section }: { section: Section }) {
  switch (section.type) {
__CASES__
    default:
      return null;
  }
}
`,

  "Hero.tsx": `export default function Hero({ section }: { section: any }) {
  return (
    <div className="py-14 text-center">
      <h2 className="mx-auto max-w-2xl text-4xl font-extrabold tracking-tight">{section.headline}</h2>
      <p className="mx-auto mt-4 max-w-xl text-lg" style={{ color: "var(--muted)" }}>
        {section.sub}
      </p>
      <div className="mt-7 flex justify-center gap-3">
        <button className="rounded-app px-6 py-2.5 font-semibold text-white" style={{ background: "var(--accent)" }}>
          {section.cta}
        </button>
        {section.secondaryCta && (
          <button className="rounded-app border px-6 py-2.5 font-semibold" style={{ borderColor: "var(--border)" }}>
            {section.secondaryCta}
          </button>
        )}
      </div>
    </div>
  );
}
`,

  "Stats.tsx": `export default function Stats({ section }: { section: any }) {
  return (
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
      {section.items.map((it: any) => (
        <div key={it.label} className="card">
          <div className="text-xs font-medium uppercase tracking-wide" style={{ color: "var(--muted)" }}>
            {it.label}
          </div>
          <div className="mt-1 text-2xl font-bold">{it.value}</div>
          {it.delta && (
            <div className="mt-1 text-xs font-semibold" style={{ color: it.delta.startsWith("-") ? "#f43f5e" : "var(--accent)" }}>
              {it.delta}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}
`,

  "ChartCard.tsx": `export default function ChartCard({ section }: { section: any }) {
  const w = 640, h = 220, pad = 30;
  const max = Math.max(...section.series, 1);
  const n = section.series.length;
  const innerW = w - pad * 2, innerH = h - pad * 2;

  return (
    <div className="card">
      <h3 className="mb-3 text-sm font-semibold">{section.title}</h3>
      <svg viewBox={\`0 0 \${w} \${h}\`} className="w-full">
        {section.kind === "bar"
          ? section.series.map((v: number, i: number) => {
              const bw = (innerW / n) * 0.55;
              const bh = (v / max) * innerH;
              const x = pad + (innerW / n) * i + (innerW / n - bw) / 2;
              return <rect key={i} x={x} y={h - pad - bh} width={bw} height={bh} rx={5} fill="var(--accent)" opacity={0.85} />;
            })
          : (() => {
              const pts = section.series.map((v: number, i: number) => [
                pad + (innerW / Math.max(n - 1, 1)) * i,
                h - pad - (v / max) * innerH,
              ]);
              const d = pts.map((p: number[], i: number) => \`\${i === 0 ? "M" : "L"}\${p[0]},\${p[1]}\`).join(" ");
              return (
                <>
                  {section.kind === "area" && (
                    <path d={\`\${d} L\${pts[pts.length - 1][0]},\${h - pad} L\${pad},\${h - pad} Z\`} fill="var(--accent)" opacity={0.14} />
                  )}
                  <path d={d} fill="none" stroke="var(--accent)" strokeWidth={2.5} strokeLinecap="round" />
                  {pts.map((p: number[], i: number) => (
                    <circle key={i} cx={p[0]} cy={p[1]} r={3.5} fill="var(--accent)" />
                  ))}
                </>
              );
            })()}
        {section.labels.map((l: string, i: number) => (
          <text
            key={l}
            x={section.kind === "bar" ? pad + (innerW / n) * i + innerW / n / 2 : pad + (innerW / Math.max(n - 1, 1)) * i}
            y={h - 8}
            fontSize={10}
            fill="var(--muted)"
            textAnchor="middle"
          >
            {l}
          </text>
        ))}
      </svg>
    </div>
  );
}
`,

  "DataTable.tsx": `export default function DataTable({ section }: { section: any }) {
  return (
    <div className="card overflow-x-auto">
      <h3 className="mb-3 text-sm font-semibold">{section.title}</h3>
      <table className="w-full text-sm">
        <thead>
          <tr>
            {section.columns.map((c: string) => (
              <th key={c} className="border-b pb-2 text-left text-xs font-semibold uppercase tracking-wide" style={{ color: "var(--muted)", borderColor: "var(--border)" }}>
                {c}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {section.rows.map((row: string[], ri: number) => (
            <tr key={ri}>
              {row.map((cell, ci) => (
                <td key={ci} className="border-b py-2.5 pr-3" style={{ borderColor: "var(--border)" }}>
                  {ci === row.length - 1 ? (
                    <span className="rounded-full border px-2 py-0.5 text-xs font-semibold" style={{ borderColor: "var(--accent)", color: "var(--accent)" }}>
                      {cell}
                    </span>
                  ) : (
                    cell
                  )}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
`,

  "CardsGrid.tsx": `export default function CardsGrid({ section }: { section: any }) {
  return (
    <div>
      {section.title && <h2 className="mb-4 text-center text-xl font-bold">{section.title}</h2>}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {section.items.map((it: any) => (
          <div key={it.title} className="card">
            <div className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg text-sm" style={{ background: "color-mix(in srgb, var(--accent) 15%, transparent)", color: "var(--accent)" }}>
              ✦
            </div>
            <h4 className="text-sm font-semibold">{it.title}</h4>
            <p className="mt-1 text-sm leading-relaxed" style={{ color: "var(--muted)" }}>
              {it.desc}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}
`,

  "Pricing.tsx": `export default function Pricing({ section }: { section: any }) {
  return (
    <div>
      <h2 className="mb-4 text-center text-xl font-bold">{section.title}</h2>
      <div className="grid gap-3 md:grid-cols-3">
        {section.tiers.map((t: any) => (
          <div key={t.name} className="card relative flex flex-col" style={t.highlight ? { borderColor: "var(--accent)" } : undefined}>
            {t.highlight && (
              <span className="absolute -top-2.5 left-1/2 -translate-x-1/2 rounded-full px-3 py-0.5 text-[10px] font-bold text-white" style={{ background: "var(--accent)" }}>
                POPULAR
              </span>
            )}
            <h4 className="font-semibold">{t.name}</h4>
            <div className="mt-2 text-3xl font-extrabold">{t.price}</div>
            <div className="mb-4 text-xs" style={{ color: "var(--muted)" }}>{t.period}</div>
            <ul className="mb-4 flex-1 space-y-2 text-sm" style={{ color: "var(--muted)" }}>
              {t.features.map((f: string) => (
                <li key={f}>✓ {f}</li>
              ))}
            </ul>
            <button
              className="rounded-app py-2 text-sm font-semibold"
              style={t.highlight ? { background: "var(--accent)", color: "#fff" } : { border: "1px solid var(--border)" }}
            >
              Choose {t.name}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
`,

  "FormCard.tsx": `import { useState } from "react";

export default function FormCard({ section }: { section: any }) {
  const [saved, setSaved] = useState(false);
  return (
    <div className="card max-w-md">
      <h3 className="text-sm font-semibold">{section.title}</h3>
      {section.sub && <p className="mt-1 text-sm" style={{ color: "var(--muted)" }}>{section.sub}</p>}
      <form
        className="mt-4 flex flex-col gap-3"
        onSubmit={(e) => {
          e.preventDefault();
          setSaved(true);
          setTimeout(() => setSaved(false), 2000);
        }}
      >
        {section.fields.map((f: any) => (
          <label key={f.label} className="text-xs font-semibold">
            {f.label}
            <input
              type={f.inputType}
              placeholder={f.placeholder}
              className="mt-1 w-full rounded-app border bg-transparent px-3 py-2 text-sm font-normal outline-none"
              style={{ borderColor: "var(--border)" }}
            />
          </label>
        ))}
        <button type="submit" className="self-start rounded-app px-5 py-2 text-sm font-semibold text-white" style={{ background: "var(--accent)" }}>
          {saved ? "Saved ✓" : section.submitLabel}
        </button>
      </form>
    </div>
  );
}
`,

  "TodoList.tsx": `import { useState } from "react";

export default function TodoList({ section }: { section: any }) {
  const [items, setItems] = useState<{ text: string; done: boolean }[]>(section.items);
  const [draft, setDraft] = useState("");

  return (
    <div className="card">
      <h3 className="mb-3 text-sm font-semibold">{section.title}</h3>
      <div className="flex flex-col gap-2">
        {items.map((it, i) => (
          <button
            key={i}
            onClick={() => setItems(items.map((x, xi) => (xi === i ? { ...x, done: !x.done } : x)))}
            className="flex items-center gap-3 rounded-app border px-3 py-2.5 text-left text-sm"
            style={{ borderColor: "var(--border)" }}
          >
            <span
              className="flex h-5 w-5 items-center justify-center rounded-md border text-[10px] text-white"
              style={it.done ? { background: "var(--accent)", borderColor: "var(--accent)" } : { borderColor: "var(--border)" }}
            >
              {it.done ? "✓" : ""}
            </span>
            <span style={it.done ? { color: "var(--muted)", textDecoration: "line-through" } : undefined}>{it.text}</span>
          </button>
        ))}
      </div>
      <form
        className="mt-3 flex gap-2"
        onSubmit={(e) => {
          e.preventDefault();
          if (!draft.trim()) return;
          setItems([...items, { text: draft.trim(), done: false }]);
          setDraft("");
        }}
      >
        <input
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          placeholder="Add a task…"
          className="flex-1 rounded-app border bg-transparent px-3 py-2 text-sm outline-none"
          style={{ borderColor: "var(--border)" }}
        />
        <button className="rounded-app px-4 text-sm font-semibold text-white" style={{ background: "var(--accent)" }}>
          Add
        </button>
      </form>
    </div>
  );
}
`,

  "Booking.tsx": `import { useState } from "react";

export default function Booking({ section }: { section: any }) {
  const [day, setDay] = useState<string>(section.days[0]);
  const [slot, setSlot] = useState<string | null>(null);

  return (
    <div className="card">
      <h3 className="mb-3 text-sm font-semibold">{section.title}</h3>
      <div className="mb-4 flex flex-wrap gap-2">
        {section.days.map((d: string) => (
          <button
            key={d}
            onClick={() => setDay(d)}
            className="rounded-app border px-4 py-2 text-sm font-semibold"
            style={day === d ? { background: "var(--accent)", color: "#fff", borderColor: "var(--accent)" } : { borderColor: "var(--border)" }}
          >
            {d}
          </button>
        ))}
      </div>
      <div className="grid grid-cols-3 gap-2 sm:grid-cols-5">
        {section.slots.map((s: string) => (
          <button
            key={s}
            onClick={() => setSlot(s)}
            className="rounded-app border py-2 text-sm font-semibold"
            style={slot === s ? { background: "var(--accent)", color: "#fff", borderColor: "var(--accent)" } : { borderColor: "var(--border)" }}
          >
            {s}
          </button>
        ))}
      </div>
      {slot && (
        <div className="mt-4 rounded-app border px-4 py-3 text-sm font-semibold" style={{ borderColor: "var(--accent)" }}>
          ✓ Booked: {day} at {slot} — confirmation sent!
        </div>
      )}
    </div>
  );
}
`,

  "Testimonials.tsx": `export default function Testimonials({ section }: { section: any }) {
  return (
    <div>
      <h2 className="mb-4 text-center text-xl font-bold">{section.title}</h2>
      <div className="grid gap-3 md:grid-cols-3">
        {section.items.map((t: any) => (
          <div key={t.author} className="card">
            <p className="text-sm leading-relaxed">&ldquo;{t.quote}&rdquo;</p>
            <div className="mt-3 text-sm font-semibold">{t.author}</div>
            <div className="text-xs" style={{ color: "var(--muted)" }}>{t.role}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
`,

  "CtaBanner.tsx": `export default function CtaBanner({ section }: { section: any }) {
  return (
    <div
      className="rounded-app border px-6 py-12 text-center"
      style={{ borderColor: "var(--accent)", background: "color-mix(in srgb, var(--accent) 10%, transparent)" }}
    >
      <h2 className="text-2xl font-bold">{section.headline}</h2>
      <p className="mx-auto mt-2 max-w-md text-sm" style={{ color: "var(--muted)" }}>{section.sub}</p>
      <button className="mt-5 rounded-app px-6 py-2.5 font-semibold text-white" style={{ background: "var(--accent)" }}>
        {section.cta}
      </button>
    </div>
  );
}
`,

  "LoginCard.tsx": `export default function LoginCard({ section }: { section: any }) {
  return (
    <div className="card mx-auto w-full max-w-sm text-center">
      <h3 className="font-semibold">{section.title}</h3>
      <p className="mt-1 text-sm" style={{ color: "var(--muted)" }}>{section.sub}</p>
      <form className="mt-4 flex flex-col gap-3 text-left" onSubmit={(e) => e.preventDefault()}>
        <input type="email" placeholder="you@example.com" className="rounded-app border bg-transparent px-3 py-2 text-sm outline-none" style={{ borderColor: "var(--border)" }} />
        <input type="password" placeholder="••••••••" className="rounded-app border bg-transparent px-3 py-2 text-sm outline-none" style={{ borderColor: "var(--border)" }} />
        <button className="rounded-app py-2 font-semibold text-white" style={{ background: "var(--accent)" }}>
          Sign in
        </button>
      </form>
    </div>
  );
}
`,

  "CustomBlock.tsx": `/**
 * Renders an AI-generated self-contained mini app (game, tool, canvas…)
 * inside an isolated sandboxed iframe.
 */
export default function CustomBlock({ section }: { section: any }) {
  return (
    <div className="card">
      {section.title && <h3 className="mb-3 text-sm font-semibold">{section.title}</h3>}
      <iframe
        title={section.title ?? "Custom app"}
        sandbox="allow-scripts"
        srcDoc={section.html}
        style={{ width: "100%", height: section.height ?? 560, border: 0, borderRadius: 8, background: "#fff", display: "block" }}
      />
    </div>
  );
}
`,

  "ActivityFeed.tsx": `export default function ActivityFeed({ section }: { section: any }) {
  return (
    <div className="card">
      <h3 className="mb-2 text-sm font-semibold">{section.title}</h3>
      <div className="divide-y" style={{ borderColor: "var(--border)" }}>
        {section.items.map((it: any, i: number) => (
          <div key={i} className="flex items-start gap-3 py-3 text-sm" style={{ borderColor: "var(--border)" }}>
            <span className="mt-1.5 h-2 w-2 shrink-0 rounded-full" style={{ background: "var(--accent)" }} />
            <span className="flex-1">{it.text}</span>
            <span className="whitespace-nowrap text-xs" style={{ color: "var(--muted)" }}>{it.time}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
`,
};

const SECTION_COMPONENT_MAP: Record<SectionType, { file: string; name: string }> = {
  hero: { file: "Hero.tsx", name: "Hero" },
  stats: { file: "Stats.tsx", name: "Stats" },
  chart: { file: "ChartCard.tsx", name: "ChartCard" },
  table: { file: "DataTable.tsx", name: "DataTable" },
  cards: { file: "CardsGrid.tsx", name: "CardsGrid" },
  pricing: { file: "Pricing.tsx", name: "Pricing" },
  form: { file: "FormCard.tsx", name: "FormCard" },
  todo: { file: "TodoList.tsx", name: "TodoList" },
  booking: { file: "Booking.tsx", name: "Booking" },
  testimonials: { file: "Testimonials.tsx", name: "Testimonials" },
  cta: { file: "CtaBanner.tsx", name: "CtaBanner" },
  login: { file: "LoginCard.tsx", name: "LoginCard" },
  activity: { file: "ActivityFeed.tsx", name: "ActivityFeed" },
  custom: { file: "CustomBlock.tsx", name: "CustomBlock" },
};

function sectionRenderer(used: Set<SectionType>): string {
  const imports = Array.from(used)
    .map((t) => {
      const c = SECTION_COMPONENT_MAP[t];
      return `import ${c.name} from "./${c.file.replace(".tsx", "")}";`;
    })
    .join("\n");
  const cases = Array.from(used)
    .map((t) => {
      const c = SECTION_COMPONENT_MAP[t];
      return `    case "${t}":\n      return <${c.name} section={section} />;`;
    })
    .join("\n");
  return COMPONENT_SOURCES["SectionRenderer.tsx"]
    .replace("__IMPORTS__", imports)
    .replace("__CASES__", cases);
}

function appTsx(bp: Blueprint): string {
  return `import { useState } from "react";
import { blueprint } from "./data/blueprint";
import Layout from "./components/Layout";
import SectionRenderer from "./components/SectionRenderer";

export default function App() {
  const [activePage, setActivePage] = useState(blueprint.pages[0].id);
  const page = blueprint.pages.find((p) => p.id === activePage) ?? blueprint.pages[0];

  return (
    <Layout activePage={activePage} onNavigate={setActivePage}>
      {page.sections.map((section, i) => (
        <SectionRenderer key={i} section={section} />
      ))}
    </Layout>
  );
}
`;
}

function readme(bp: Blueprint): string {
  return `# ${bp.name}

${bp.description}

> Generated with **ForgeAI** — an AI app builder.

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

Then open http://localhost:5173

## Stack

- Vite + React 18 + TypeScript
- Tailwind CSS
- Blueprint-driven rendering: all content lives in \`src/data/blueprint.ts\`

## Structure

- \`src/App.tsx\` — root component with page navigation
- \`src/components/\` — typed section components (stats, charts, tables, …)
- \`src/data/blueprint.ts\` — the structured content of your app; edit it and the UI updates
- \`src/types.ts\` — shared types
${bp.features.supabase.enabled ? "- `src/lib/supabase.ts` — Supabase client (set env vars in `.env`)\n" : ""}
## Theme

- Mode: **${bp.theme.mode}**
- Accent: **${bp.theme.accentName}** (${bp.theme.accent})
- Radius: ${bp.theme.radius}px
`;
}

function supabaseClient(): string {
  return `/**
 * Supabase client — generated by ForgeAI.
 *
 * 1. Create a project at https://supabase.com
 * 2. Copy your URL + anon key into .env:
 *      VITE_SUPABASE_URL=...
 *      VITE_SUPABASE_ANON_KEY=...
 */
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL ?? "";
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY ?? "";

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
`;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

export function generateProjectFiles(bp: Blueprint): AppFile[] {
  const used = usedSectionTypes(bp);

  const files: AppFile[] = [
    { path: "package.json", content: packageJson(bp) },
    { path: "vite.config.ts", content: VITE_CONFIG },
    { path: "tsconfig.json", content: TSCONFIG },
    { path: "index.html", content: indexHtml(bp) },
    { path: "postcss.config.js", content: POSTCSS },
    { path: "tailwind.config.js", content: tailwindConfig(bp) },
    { path: "src/main.tsx", content: MAIN_TSX },
    { path: "src/index.css", content: indexCss(bp) },
    { path: "src/App.tsx", content: appTsx(bp) },
    { path: "src/types.ts", content: typesFile() },
    { path: "src/data/blueprint.ts", content: blueprintData(bp) },
    { path: "src/components/Layout.tsx", content: COMPONENT_SOURCES["Layout.tsx"] },
    { path: "src/components/SectionRenderer.tsx", content: sectionRenderer(used) },
    { path: "README.md", content: readme(bp) },
  ];

  for (const t of Array.from(used)) {
    const c = SECTION_COMPONENT_MAP[t];
    files.push({
      path: `src/components/${c.file}`,
      content: COMPONENT_SOURCES[c.file],
    });
  }

  if (bp.features.supabase.enabled) {
    files.push({ path: "src/lib/supabase.ts", content: supabaseClient() });
    files.push({
      path: ".env.example",
      content: "VITE_SUPABASE_URL=\nVITE_SUPABASE_ANON_KEY=\n",
    });
  }

  return files.sort((a, b) => a.path.localeCompare(b.path));
}
